# Site settings
title: Centro Universitário Católica de Santa Catarina
email: lucas@lucas.ninja
description: > # this means to ignore newlines until "baseurl:"
  Graduação, pós-graduação, Centro Universitário, Jaraguá do Sul, Joinville, Pesquisa Santa Catarina, Católica de Santa Catarina, Católica SC.
baseurl: "/catolicasc" # the subpath of your site, e.g. /blog/
url: "http://bsi.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

exclude: ['node_modules', 'package.json', 'gulpfile.js']

include: ['.gitignore']
